 const NEW_STUDENT = 'NEW_STUDENT'
 const REMOVE_STUDENT = 'REMOVE_STUDENT'
 const REMOVE_ALL_STUDENT = 'REMOVE_ALL_STUDENT'

 const ADD_REWARD = 'ADD_REWARD'
 const REMOVE_REWARD = 'REMOVE_REWARD'
 const REMOVE_ALL_REWARD = 'REMOVE_ALL_REWARD'

export default {
    NEW_STUDENT,
    REMOVE_STUDENT,
    REMOVE_ALL_STUDENT,
    ADD_REWARD,
    REMOVE_REWARD,
    REMOVE_ALL_REWARD
}
